version: '3.4'

services:

  frontend:
  
    build: ./frontend  
    
    volumes:
      - ./frontend:/app  
    ports:
      - "3000:3000"  
  backend:
    build: ./backend  
    
    environment:
      DATABASE_HOST: "localhost"
      DATABASE_USER: "laptop"
      DATABASE_PASSWORD: "Sanj1999.."  
    ports:
      - "3001:3001"  

      
